version: '3'

services:
  nginx-proxy:
    container_name: ab_nginx_proxy
    build: ./docker/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  mysql-8:
    image: arm64v8/mysql:8.0.28-oracle
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: ab_mysql_8
    ports:
      - "33060:3306"
    volumes:
      - ./db-data:/var/lib/mysql:delegated
    working_dir: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  hackday-nginx:
    container_name: hackday_nginx
    build: ./docker/nginx
    environment:
      - VIRTUAL_HOST=hackday.test
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - eightone-fpm

  eightone-fpm:
    container_name: ab_php-81-fpm
    build: docker/php-81-fpm
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www
    links:
      - mysql-8
